[package]
name = "rust-auth-server"
version = "0.0.1"
authors = ["Inver"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
