[package]
name = "rust-auth-server"
version = "0.0.1"
authors = ["Inver"]
edition = "2018"

[dependencies]
rocket = "0.4.6"
rocket_contrib = "0.4.6"
aerospike = "1.0.0"
serde = "1.0.118"
jsonwebtoken = "7.2.0"